services:
  web:
    image: ghcr.io/wrenchpilot/apache-php82-oci8:latest
    container_name: apache-php82-oci8
    ports:
      - "80:80"
    volumes:
      - ./index.php:/var/www/html/index.php # Test
      #- /opt/html:/var/www/html # Prod
    restart: always