services:
  web:
    image: ghcr.io/wrenchpilot/apache-php82-oci8:latest
    container_name: apache-php82-oci8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "80:80"
    volumes:
      - ./index.php:/var/www/html/index.php # Test
      - ./oci.php:/var/www/html/oci.php # OCI Test
      #- /opt/html:/var/www/html # Prod
    restart: always