name: Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build the Docker image with two tags
      - name: Build Docker image with tags
        run: |
          TIMESTAMP=$(date +%s)
          docker build -t gt-apache-php82-oci8:latest -t gt-apache-php82-oci8:$TIMESTAMP .

      # Optionally, test the Docker image
      - name: Test Docker image
        run: |
          docker run --rm gt-apache-php82-oci8:latest php -v
