name: Build Docker Image

on:
  push:
    paths:
      - Dockerfile
      - .github/workflows/docker-image.yml
  pull_request:
    paths:
      - Dockerfile
      - .github/workflows/docker-image.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # Build the Docker image with two tags
      - name: Build Docker image with tags
        run: |
          DOCKER_BUILDKIT=1 docker build --platform linux/amd64 -t apache-php82-oci8:latest .

      # Optionally, test the Docker image
      - name: Test Docker image
        run: |
          docker run --rm apache-php82-oci8:latest php -v

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker tag apache-php82-oci8:latest ghcr.io/wrenchpilot/apache-php82-oci8:latest
          docker push ghcr.io/wrenchpilot/apache-php82-oci8:latest

